name = "omnexa-web-pixel"
type = "web_pixel_extension"
uid = "19ae3466-acba-285c-c033-316b9f18f5736af1d9c0"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.accountID]
name = "Account ID"
description = "Account ID"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
