# Generated by Django 4.1.2 on 2026-06-09 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('preview_text', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('campaign_type', models.CharField(default='Promotional', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Promotional', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('preview_text', models.CharField(blank=True, max_length=500, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('editor_json', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='Stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('filter_config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('cached_contact_count', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_segments', to='Stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('personalization', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='EmailMarketing.emailcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign_recipients', to='Stores.contact')),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='EmailMarketing.emailsegment'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='Stores.store'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='EmailMarketing.emailtemplate'),
        ),
        migrations.CreateModel(
            name='EmailBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_logo_url', models.TextField(blank=True, null=True)),
                ('brand_color', models.CharField(default='#3B82F6', max_length=20)),
                ('default_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notify_campaign_sent', models.BooleanField(default=True)),
                ('notify_weekly_reports', models.BooleanField(default=True)),
                ('notify_new_subscriber', models.BooleanField(default=False)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_brand_settings', to='Stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stores.contact')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_unsubscribes', to='Stores.store')),
            ],
            options={
                'unique_together': {('store', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='emailcampaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='EmailMarket_campaig_52750e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaignrecipient',
            index=models.Index(fields=['tracking_token'], name='EmailMarket_trackin_076087_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailcampaignrecipient',
            unique_together={('campaign', 'contact')},
        ),
    ]
