# Generated by Django 4.1.2 on 2026-07-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('EmailMarketing', '0002_emailcampaign_wizard_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file_url', models.TextField()),
                ('client_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(default='image', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_media', to='Accounts.store')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='EmailMarketing.emailtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
