# Generated by Django 4.1.2 on 2026-07-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_store_sendgrid_api_key_remove_store_smtp_host_and_more'),
        ('EmailMarketing', '0003_emailtemplatemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSenderIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mode', models.CharField(default='platform_domain', max_length=50)),
                ('brand_name', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to_email', models.EmailField(max_length=254)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('sendgrid_domain_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_records', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_identities', to='Accounts.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='storesenderidentity',
            index=models.Index(fields=['store', 'is_active'], name='EmailMarket_store_i_cb0ad9_idx'),
        ),
    ]
