# Generated by Django 4.1.2 on 2026-08-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0004_storesenderidentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='unsubscribe_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
