# Generated by Django 4.1.2 on 2026-08-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0005_emailcampaign_unsubscribe_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='editor_json',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='preview_text',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='discount_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
