# Generated by Django 4.1.2 on 2026-08-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0007_emailtemplate_editor_json_emailtemplate_is_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='add_to_cart_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='checkout_started_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='page_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='add_to_cart_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='checkout_started_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='page_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
