# Generated by Django 4.1.2 on 2026-07-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_remove_store_sendgrid_api_key_remove_store_smtp_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=500, unique=True)),
                ('shopify_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_settings', to='Accounts.store')),
            ],
        ),
    ]
