# Generated by Django 4.1.2 on 2026-07-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0002_alter_shopifysettings_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysettings',
            name='shopify_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifysettings',
            name='shopify_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
