# Generated by Django 4.1.2 on 2026-08-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0003_shopifysettings_shopify_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysettings',
            name='custom_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifysettings',
            name='custom_api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
