# Generated by Django 4.1.2 on 2026-06-14 20:54

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('shop_url', models.CharField(max_length=500)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_provider', models.CharField(default='sendgrid', max_length=50)),
                ('sendgrid_api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='Accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator')], default='admin', max_length=20)),
                ('assigned_stores', models.ManyToManyField(blank=True, related_name='assigned_users', to='Accounts.store')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('accept_email_marketing', models.BooleanField(default=False)),
                ('accept_email_marketing_at', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='Accounts.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['client', 'is_active'], name='Accounts_st_client__1f6325_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['api_key'], name='Accounts_st_api_key_279d00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('client', 'shop_url')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['store', 'accept_email_marketing'], name='Accounts_co_store_i_1cd1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['store', 'email'], name='Accounts_co_store_i_7b2129_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['store', 'last_order_at'], name='Accounts_co_store_i_e708b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('store', 'email')},
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['user', 'is_active'], name='Accounts_cl_user_id_bb0b08_idx'),
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['client', 'is_active'], name='Accounts_cl_client__e924e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientuser',
            unique_together={('user', 'client')},
        ),
    ]
