# Generated by Django 4.1.2 on 2026-07-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='sendgrid_api_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_use_tls',
        ),
        migrations.RemoveField(
            model_name='store',
            name='smtp_username',
        ),
    ]
