# Generated by Django 4.1.2 on 2026-08-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0004_storesenderidentity_and_more'),
        ('Accounts', '0004_contact_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='EmailMarketing.emailsegment'),
        ),
    ]
