# Generated by Django 4.1.2 on 2026-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_contact_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
