# Generated by Django 4.1.2 on 2026-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_store_store_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
