# Generated by Django 4.1.2 on 2026-06-09 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('shop_url', models.CharField(max_length=500)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_provider', models.CharField(default='sendgrid', max_length=50)),
                ('sendgrid_api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='Accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('accept_email_marketing', models.BooleanField(default=False)),
                ('accept_email_marketing_at', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Stores.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['client', 'is_active'], name='Stores_stor_client__6f5145_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['api_key'], name='Stores_stor_api_key_792e9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('client', 'shop_url')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['store', 'accept_email_marketing'], name='Stores_cont_store_i_adbb57_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['store', 'email'], name='Stores_cont_store_i_d5d859_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['store', 'last_order_at'], name='Stores_cont_store_i_f45601_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('store', 'email')},
        ),
    ]
